// @vitest-environment jsdom
import { cleanup, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, describe, expect, it, vi } from "vitest";
import type { TripRecord, UserRecord } from "../../firebase/contracts";
import { joinTrip, normalizeJoinCode, OnboardingFlow, submitNewTrip, type OnboardingBackend } from "./OnboardingFlow";

const profile: UserRecord = { uid: "user-1", displayName: "Khanh", email: "khanh@example.com", tripIds: [] };
const trip: TripRecord = { id: "trip-1", name: "Da Lat weekend", destination: "Da Lat", startDate: "2026-07-30", endDate: "2026-08-01", leadId: profile.uid, joinCode: "ABCDEFGHJKLMNPQR" };
function createBackend(overrides: Partial<OnboardingBackend> = {}): OnboardingBackend { return { createTrip: vi.fn().mockResolvedValue(trip), joinTrip: vi.fn().mockResolvedValue(trip), ...overrides }; }
afterEach(cleanup);

describe("onboarding actions", () => {
  it("creates a trip with the backend-authenticated actor", async () => { const backend=createBackend(); await expect(submitNewTrip(backend, profile, { name: trip.name, destination: trip.destination, startDate: trip.startDate, endDate: trip.endDate })).resolves.toEqual(trip); expect(backend.createTrip).toHaveBeenCalledWith({name:trip.name,destination:trip.destination,startDate:trip.startDate,endDate:trip.endDate},profile); });
  it("normalizes a join code before the proof-backed backend call", async () => { const backend=createBackend(); expect(normalizeJoinCode(" abcd-efgh jklm-npqr ")).toBe("ABCDEFGHJKLMNPQR"); await expect(joinTrip(backend,profile," abcd-efgh jklm-npqr ")).resolves.toEqual(trip); expect(backend.joinTrip).toHaveBeenCalledWith("ABCDEFGHJKLMNPQR",profile); });
  it("rejects an invalid date range without writing", async () => { const backend=createBackend(); await expect(submitNewTrip(backend,profile,{...trip,startDate:"2026-08-01",endDate:"2026-07-30"})).rejects.toMatchObject({errors:{endDate:expect.any(String)}}); expect(backend.createTrip).not.toHaveBeenCalled(); });
});
describe("OnboardingFlow", () => {
  it("joins with a normalized proof-backed code", async () => { const backend=createBackend(); const ready=vi.fn(); const actor=userEvent.setup(); render(<OnboardingFlow backend={backend} profile={profile} onTripReady={ready}/>); expect(screen.getByRole("region",{name:"Create a new workspace"})).toBeTruthy(); expect(screen.getByRole("region",{name:"Join by code"})).toBeTruthy(); await actor.type(screen.getByLabelText("Join code"), "abcd-efgh-jklm-npqr"); await actor.click(screen.getByRole("button",{name:"Join trip"})); expect(backend.joinTrip).toHaveBeenCalledWith("ABCDEFGHJKLMNPQR", profile); expect(ready).toHaveBeenCalledWith(trip); });
  it("shows inline validation without writing", async () => { const backend=createBackend(); const actor=userEvent.setup(); render(<OnboardingFlow backend={backend} profile={profile} onTripReady={vi.fn()}/>); await actor.click(screen.getByRole("button",{name:"Create new trip"})); expect(screen.getByLabelText("Trip name").getAttribute("aria-invalid")).toBe("true"); expect(backend.createTrip).not.toHaveBeenCalled(); });
  it("locks creation while pending", async () => { let resolve:((value:TripRecord)=>void)|undefined; const backend=createBackend({createTrip:vi.fn().mockImplementation(()=>new Promise<TripRecord>((r)=>{resolve=r;}))}); const actor=userEvent.setup(); render(<OnboardingFlow backend={backend} profile={profile} onTripReady={vi.fn()}/>); await actor.type(screen.getByLabelText("Trip name"),trip.name); await actor.type(screen.getByLabelText("Destination"),trip.destination); await actor.type(screen.getByLabelText("Start date"),trip.startDate); await actor.type(screen.getByLabelText("End date"),trip.endDate); await actor.click(screen.getByRole("button",{name:"Create new trip"})); expect((screen.getByRole("button",{name:"Creating trip…"}) as HTMLButtonElement).disabled).toBe(true); resolve?.(trip); });
  it("creates a trip and hands it to App", async () => { const backend=createBackend(); const ready=vi.fn(); const actor=userEvent.setup(); render(<OnboardingFlow backend={backend} profile={profile} onTripReady={ready}/>); await actor.type(screen.getByLabelText("Trip name"),trip.name); await actor.type(screen.getByLabelText("Destination"),trip.destination); await actor.type(screen.getByLabelText("Start date"),trip.startDate); await actor.type(screen.getByLabelText("End date"),trip.endDate); await actor.click(screen.getByRole("button",{name:"Create new trip"})); expect(await screen.findByText("Trip created.")).toBeTruthy(); expect(ready).toHaveBeenCalledWith(trip); });
});
